#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

if [ "no" = "no" -o "no" = no ];
then

    gen_ignore_test "Nanos++ or CUDA are disabled"
    exit
fi

source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mnvcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
MCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mnvcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
EOF

# compile_versions="\${compile_versions} nanox_cuda"
cat <<EOF
test_CC_cuda_omp="\${MCC}"
test_CXX_cuda_omp="\${MCXX}"

test_CFLAGS_cuda_omp="--ompss --cuda"
test_CXXFLAGS_cuda_omp="--ompss --cuda"
EOF

cat <<EOF
test_nolink=yes
EOF
