#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

# Parsing the test-generator arguments
parse_arguments $@

# Basic mercurium generator
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

if ! $(gcc_supports_c11);
then
    gen_ignore_test "requires g++ 4.8 or better"
    exit
fi

cat <<EOF
MCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
test_CC="\${MCXX} --profile=plaincc -std=c11"
test_CXX="do_not_use_this_profile_for_cxx"
test_FC="do_not_use_this_profile_for_fortran"

if [ "$test_nolink" = "no" -o "$TG_ARG_RUN" = "yes" ];
then
   unset test_nolink
else
   test_nolink=yes
fi
EOF
