#!/usr/bin/env bash

source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

cat <<EOF
MCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
test_CC="\${MCXX} --profile=plaincc"
test_CXX="\${MCXX} --profile=plaincxx"
test_FC="\${MCXX} --profile=plainfc"
test_noexec=yes
test_CFLAGS="\${test_CFLAGS} -y --typecheck"
test_CXXFLAGS="\${test_CXXFLAGS} -y --typecheck"
test_FFLAGS="\${test_CFLAGS} -y --typecheck"
EOF
