#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

if [ "yes" = "no" -o "no" = "no" ];
then

    gen_ignore_test "analysis or Nanos++ disabled"
    exit
fi

# Parsing the test-generator arguments
parse_arguments $@

source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

PROGRAMMING_MODEL="--openmp"

cat <<EOF
MCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
MCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
MFC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mfc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
compile_versions="\${compile_versions} nanox_mercurium"
EOF

cat <<EOF
test_CC="\${MCC} --profile=mcc"
test_CXX="\${MCXX} --profile=mcxx"
test_FC="\${MFC} --profile=mfc"

test_CFLAGS_nanox_mercurium="--analysis-check --debug-flags=analysis_verbose ${PROGRAMMING_MODEL} ${COMMON_NANOX_CFLAGS}"
test_CXXFLAGS_nanox_mercurium="--analysis-check --debug-flags=analysis_verbose ${PROGRAMMING_MODEL} ${COMMON_NANOX_CFLAGS}"
test_FFLAGS_nanox_mercurium="--analysis-check --debug-flags=analysis_verbose"

if [ "$test_nolink" == "no" -o "$TG_ARG_RUN" = "yes" ];
then
    unset test_nolink
else
    test_nolink=yes
fi
EOF
