#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

if [ "no" = "no" ];
then
    gen_ignore_test "Vectorization is disabled"
    exit
fi

if [ "no" = "no" ];
then
    gen_ignore_test "Nanos++ is disabled"
    exit
fi

# Parsing the test-generator arguments
parse_arguments $@

if [ "$TG_ARG_SVML" = "yes" ];
then
    gen_ignore_test "SVML is not supported"
    exit
fi

source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

COMMON_NANOX_CFLAGS=-DNANOX


cat <<EOF
MCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
MCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"

compile_versions="\${compile_versions} nanox_mercurium"

test_CC_nanox_mercurium="\${MCC}"
test_CXX_nanox_mercurium="\${MCXX}"

test_CFLAGS_nanox_mercurium="--simd --debug-flags=vectorization_verbose --openmp --romol -std=gnu99 ${COMMON_NANOX_CFLAGS}"
test_CXXFLAGS_nanox_mercurium="--simd --debug-flags=vectorization_verbose --openmp --romol ${COMMON_NANOX_CFLAGS}"
test_LDFLAGS_nanox_mercurium="--romol /home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
test_nolink=yes

EOF
