#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

if [ "no" = "no" ];
then
    gen_ignore_test "Nanos6 has not been configured or is being bootstrapped"
    exit
fi

if [ "$TEST_LANGUAGE" = "fortran" -a yes = no ];
then
    gen_ignore_test "Fortran tests are disabled"
    exit
fi

# Parsing the test-generator arguments
parse_arguments $@


if [ "$TG_ARG_OMPSS_2" = "yes" ];
then
    PROGRAMMING_MODEL="--ompss-2"
fi

if [ "$TG_ARG_OPENMP_COMPATIBILITY" = "yes" ];
then
    PROGRAMMING_MODEL="${PROGRAMMING_MODEL} --openmp-compatibility"
fi


if [ "$TG_ARG_CXX11" = "yes" ];
then
    if ! $(gcc_supports_cxx11);
    then
        gen_ignore_test "requires g++ 4.8 or better"
        exit
    fi
    CXX11_FLAG="-std=c++11"
fi

source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

cat <<EOF
NANOS6_CC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
NANOS6_CXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose ${CXX11_FLAG}"
NANOS6_FC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mfc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config -I/home/jmartinez/BSC/software/mcxx-2.1.0/support/openmp/fortran --verbose"
EOF


# COMMON_NANOS6_CFLAGS="-DNANOS6"

cat <<EOF
compile_versions="\${compile_versions} nanos6_mercurium"
runner_nanos6_mercurium=runner_taskset

test_CC_nanos6_mercurium="\${NANOS6_CC}"
test_CXX_nanos6_mercurium="\${NANOS6_CXX}"
test_FC_nanos6_mercurium="\${NANOS6_FC}"

test_FFLAGS="\${test_FFLAGS} --fpc=/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/fortran/.libs/mf03-prescanner"

test_CFLAGS_nanos6_mercurium=" ${PROGRAMMING_MODEL} ${COMMON_NANOS6_CFLAGS} "
test_CXXFLAGS_nanos6_mercurium=" ${PROGRAMMING_MODEL} ${COMMON_NANOS6_CFLAGS} "
test_FFLAGS_nanos6_mercurium=" ${PROGRAMMING_MODEL} "

test_LDFLAGS_nanos6_mercurium="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"

EOF

if [ "$TEST_LANGUAGE" = "c" ];
then
  if [ ! -z "" ];
  then
cat <<EOF
NANOS6_IMCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=imcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
compile_versions="\${compile_versions} nanos6_imcc"
runner_nanos6_imcc=runner_taskset
test_CC_nanos6_imcc="\${NANOS6_IMCC}"
test_CFLAGS_nanos6_imcc=" ${PROGRAMMING_MODEL} ${COMMON_NANOS6_CFLAGS} "
test_LDFLAGS_nanos6_imcc="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
  fi

  if [ ! -z "" ];
  then
cat <<EOF
NANOS6_XLMCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=xlmcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
compile_versions="\${compile_versions} nanos6_xlmcc"
runner_nanos6_xlmcc=runner_taskset
test_CC_nanos6_xlmcc="\${NANOS6_XLMCC}"
test_CFLAGS_nanos6_xlmcc=" ${PROGRAMMING_MODEL} ${COMMON_NANOS6_CFLAGS} "
test_LDFLAGS_nanos6_xlmcc="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
  fi
fi

if [ "$TEST_LANGUAGE" = "cpp" ];
then
  if [ ! -z "" ];
  then
cat <<EOF
NANOS6_IMCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=imcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose ${CXX11_FLAG}"
compile_versions="\${compile_versions} nanos6_imcxx"
runner_nanos6_imcxx=runner_taskset
test_CXX_nanos6_imcxx="\${NANOS6_IMCXX}"
test_CXXFLAGS_nanos6_imcxx=" ${PROGRAMMING_MODEL} ${COMMON_NANOS6_CFLAGS} "
test_LDFLAGS_nanos6_imcxx="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
  fi

  if [ ! -z "" ];
  then
cat <<EOF
NANOS6_XLMCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=xlmcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose ${CXX11_FLAG}"
compile_versions="\${compile_versions} nanos6_xlmcxx"
runner_nanos6_xlmcxx=runner_taskset
test_CXX_nanos6_xlmcxx="\${NANOS6_XLMCXX}"
test_CXXFLAGS_nanos6_xlmcxx=" ${PROGRAMMING_MODEL} ${COMMON_NANOS6_CFLAGS} "
test_LDFLAGS_nanos6_xlmcxx="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
  fi
fi

if [ "$TEST_LANGUAGE" = "fortran" ];
then
  if [ ! -z "" ];
  then
cat <<EOF
NANOS6_IMFC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=imfc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
compile_versions="\${compile_versions} nanos6_imfc"
runner_nanos6_imfc=runner_taskset
test_FC_nanos6_imfc="\${NANOS6_IMFC}"
test_FFLAGS_nanos6_imfc=" ${PROGRAMMING_MODEL} "
test_LDFLAGS_nanos6_imfc="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
test_ENV_nanos6_imfc="FOR_IGNORE_EXCEPTIONS=1"
EOF
  fi

  if [ ! -z "" ];
  then
cat <<EOF
NANOS6_XLMFC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=xlmfc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
compile_versions="\${compile_versions} nanos6_xlmfc"
runner_nanos6_xlmfc=runner_taskset
test_FC_nanos6_xlmfc="\${NANOS6_XLMFC}"
test_FFLAGS_nanos6_xlmfc=" ${PROGRAMMING_MODEL} "
test_LDFLAGS_nanos6_xlmfc="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
  fi
fi


# for nanos6_variant in @NANOS6_VARIANTS@;
for nanos6_variant in optimized;
do
    for threads in 1 2 4;
    do
        vername=nanos6_${nanos6_variant}_${threads}thread
cat <<EOF
exec_versions="\${exec_versions} $vername"
test_ENV_$vername="NANOS6_LOADER_VERBOSE=1 NANOS6='${nanos6_variant}' TASKSET_NUM_CPUS='$threads'"
EOF
        unset vername
    done
done
