#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

# Unmaintained tests
gen_ignore_test "Unmaintained tests"
exit

if [ "no" = "no" ];
then
    gen_ignore_test "Vectorization is disabled"
    exit
fi

if [ "no" = "no" -o "yes" = "no" ];
then
    gen_ignore_test
    exit
fi

# Parsing the test-generator arguments
parse_arguments $@

source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
MCXX="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=mcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
EOF

COMMON_NANOX_CFLAGS=-DNANOX

SVML=
if [ "$TG_ARG_SVML" = "yes" ];
then
    SVML="--svml --fast-math"
fi

cat <<EOF
compile_versions="\${compile_versions} nanox_mercurium"

test_CC_nanox_mercurium="\${MCC}"
test_CXX_nanox_mercurium="\${MCXX}"

test_CFLAGS_nanox_mercurium="-O0 --simd --debug-flags=vectorization_verbose --openmp ${SVML} -std=gnu99 ${COMMON_NANOX_CFLAGS}"
test_CXXFLAGS_nanox_mercurium="-O0 --simd --debug-flags=vectorization_verbose --openmp ${SVML} ${COMMON_NANOX_CFLAGS}"

test_LDFLAGS_nanox_mercurium="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"

EOF



if [ ! -z "" ];
then
cat <<EOF
IMCC="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=imcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
compile_versions="\${compile_versions} nanox_imcc"
test_CC_nanox_imcc="\${IMCC}"

test_CFLAGS_nanox_imcc="-O0 --simd --debug-flags=vectorization_verbose --openmp ${SVML} --enable-ms-builtins ${PROGRAMMING_MODEL} ${COMMON_NANOX_CFLAGS}"
test_CXXFLAGS_nanox_imcc="-O0 --simd --debug-flags=vectorization_verbose --openmp ${SVML} --enable-ms-builtins ${PROGRAMMING_MODEL} ${COMMON_NANOX_CFLAGS}"

test_LDFLAGS_nanox_imcc="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF

fi

cat <<EOF
exec_versions="1thread 2thread 4thread"

test_ENV_1thread="OMP_NUM_THREADS='1'"
test_ENV_2thread="OMP_NUM_THREADS='2'"
test_ENV_4thread="OMP_NUM_THREADS='4'"
EOF
