#!/usr/bin/env bash

# Loading some test-generators utilities
source /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/test-generators-utilities

if [ -z "" ];
then
    gen_ignore_test "Intel OMP is not enabled"
    exit
fi

cat <<EOF
compile_versions="\${compile_versions} iomp_gnu"

test_CC_iomp_gnu="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=iomp-mcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
test_CXX_iomp_gnu="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=iomp-mcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"

test_CFLAGS="\${test_CFLAGS} --openmp"
test_CXXFLAGS="\${test_CXXFLAGS} --openmp"

test_LDFLAGS_iomp_gnu="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF

if [ "$TEST_LANGUAGE" = "c" -a ! -z "" ];
then
cat <<EOF
compile_versions="\${compile_versions} iomp_imcc"
test_CC_iomp_imcc="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=iomp-imcc --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
test_LDFLAGS_iomp_imcc="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
fi

if [ "$TEST_LANGUAGE" = "cpp" -a ! -z "" ];
then
cat <<EOF
compile_versions="\${compile_versions} iomp_imcxx"
test_CXX_iomp_imcxx="/home/jmartinez/BSC/software/mcxx-2.1.0/src/driver/plaincxx --output-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/tests --profile=iomp-imcxx --config-dir=/home/jmartinez/BSC/software/mcxx-2.1.0/config --verbose"
test_LDFLAGS_iomp_imcxx="/home/jmartinez/BSC/software/mcxx-2.1.0/lib/perish.o"
EOF
fi

cat <<EOF
exec_versions="\${exec_versions} 1thread 4thread"
test_ENV_1thread="OMP_NUM_THREADS='1'"
test_ENV_4thread="OMP_NUM_THREADS='4'"
EOF
