#!/usr/bin/env bash

# Restrict these tests to AMD64
if [ $(uname -m) = x86_64 ];
then
    /home/jmartinez/BSC/software/mcxx-2.1.0/tests/config/mercurium-cxx11
else
    echo "test_ignore=yes"
    echo "test_ignore_reason=\"Only run in x86_64\""
fi
